version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    assignees: [jessestricker]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    assignees: [jessestricker]
